### ISSUE TITLE
Generic parameter 'T' could not be inferred

### ISSUE THREAD

**Issue by omarojo** [SteveBarnegren/TweenKit#16]
![image](https://user-images.githubusercontent.com/995265/41450265-619019d4-701b-11e8-97c5-c8a90026ae31.png)

Any suggestion ?

**Comment by omarojo** [comment]
ohh sorry.. apparently it was the duration parameter. It had to be Double instead of CGFloat.

**Comment by SteveBarnegren** [comment]
Glad you got it working! 👍
