### ISSUE TITLE
Tap gesture in Onboarding?

### ISSUE THREAD

**Issue by IVANKRUPSKI** [SteveBarnegren/TweenKit#21]
Hello!

Is it possible to add tap gesture in on-boarding?

So that user could go to the next screen not only with swipe but also with tap (come back to the previous screen only with swipe, obviously).

Thank you.

**Comment by SteveBarnegren** [comment]
@IVANKRUPSKI Sure, it's easy enough to do!

The on-boarding example is entirely driven by a scrollview, so in order to achieve this you would simply add a button that sets the scrollview offset to the following page, and the animation will update as the scrollview scrolls.

Does that help?

**Comment by IVANKRUPSKI** [comment]
Yea, 

Thanks, Steve!
