### ISSUE TITLE
Support Swift Package Manager in Xcode 11

### ISSUE THREAD

**Issue by KaneCheshire** [SteveBarnegren/TweenKit#23]
👋 

Hey! Appreciate Xcode 11 has only just been published into beta but getting this in early so that when Xcode 11 is released it's not a surprise or last minute job for anyone :) 

Xcode 11 has incredible support for Swift Package Manager, including for iOS projects, and people will be expecting to replace pods with Packages. From what I can see it doesn't look like TweenKit yet supports SPM (which is expected because SPM was never officially supported for iOS until now), so would be good to start thinking about it.

**Comment by SteveBarnegren** [comment]
Hi @KaneCheshire 

I'm also planning on moving my projects from CocoaPods to SPM when Xcode 11 ships, so we'll definitely need to make sure that it supports SPM at least before Xcode 11 ships!

I'll likely take a look at it in a couple of weeks or so when I start developing with Xcode 11. If you do want to make a pull request in the meantime for it though I'd be happy to merge it in!

**Comment by KaneCheshire** [comment]
Sure, whoever gets their first! I'm looking a some of my pods first so I'll make sure I'm doing it properly, if this still needs doing after that I'll give it a shot :)

**Comment by SteveBarnegren** [comment]
Done! Only took a year to get around to it! 😄

https://github.com/SteveBarnegren/TweenKit/releases/tag/1.0.0

**Comment by KaneCheshire** [comment]
Nice one! Sorry I never did it myself 🙈 I've finished my repos now too though thankfully!
