### ISSUE TITLE
Onboarding loop animations?

### ISSUE THREAD

**Issue by IVANKRUPSKI** [SteveBarnegren/TweenKit#24]
Is it possible to somehow make a loop of those swipe animations in onboarding?

So that a user could swipe it without necessity to swipe back.

**Comment by SteveBarnegren** [comment]
Hi @IVANKRUPSKI 

Sure, you could do this. TweenKit is more of an animation engine than an onboarding template, so you would have to build the implementation that you wanted yourself using TweenKit to power it.

Essentially I think you'd just have to build a final step in the animation that animates back to the starting state. You would then be able to 'reset' once you had scrolled to the end.

At the moment I don't think it's possible to actually scrub an action that doesn't have a fixed time (like an infinitely repeating one). I hadn't considered this use case, but it sounds like it might be valuable to add that at some point. You should definitely be able to make it work with the resetting method though.
