### ISSUE TITLE
Custom easing function

### ISSUE THREAD

**Issue by cedicaks** [SteveBarnegren/TweenKit#26]
Hi. Is it possible to add or use custom easing functions?

**Comment by SteveBarnegren** [comment]
Hi @cedicaks 

It's not possible at the moment, but it would be pretty easy to add that functionality if you wanted to.

If you take a look at `Easing.swift`, you could probably add an additional case that could take a function `.custom((Double) -> Double)`. I think that would be a really quick and easy change to make. If you do that and want to open a pull request back to the main project then I'd be happy to merge that feature in!
